services:
  - type: web
    name: issuetracker-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_URL
        fromDatabase:
          name: issuetracker-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: issuetracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: issuetracker-db
          property: password
      - key: ALLOWED_ORIGINS
        value: https://YOUR_GITHUB_USERNAME.github.io

databases:
  - name: issuetracker-db
    plan: free
